version: '3'
services:
  postgresql:
    image: postgres
    ports:
      - "5432:5432"

  djorm:
    build: .
    depends_on:
      - postgresql
    environment:
      - POSTGRES_USER=postgres
    links:
      - postgresql
    ports:
      - "8000:8000"
    volumes:
      - .:/code:cached
